#!/usr/bin/env -S uv run --script
#MISE description="Extract content after frontmatter"
#USAGE arg "<file>" help="Markdown file to read"
# /// script
# dependencies = ["pyyaml"]
# ///

import os
import sys

sys.path.insert(0, os.environ["MISE_CONFIG_ROOT"] + "/lib")
from farts import get_body, resolve_path

path = resolve_path(os.environ["usage_file"])

with open(path) as f:
    text = f.read()

print(get_body(text), end="")
