#!/usr/bin/env -S uv run --script
#MISE description="Filter files by frontmatter fields"
#USAGE arg "<expr>" help="Query expression (e.g. 'tags contains guide')"
#USAGE arg "<files>" var=#true help="Markdown files to search"
# /// script
# dependencies = ["pyyaml"]
# ///

import os
import shlex
import sys

sys.path.insert(0, os.environ["MISE_CONFIG_ROOT"] + "/lib")
from farts import parse_frontmatter, matches_query, resolve_path

expr = os.environ["usage_expr"]
files = shlex.split(os.environ.get("usage_files", ""))

for path in files:
    path = resolve_path(path)
    try:
        with open(path) as f:
            text = f.read()
        fields, _, _ = parse_frontmatter(text)
        if matches_query(fields, expr):
            print(path)
    except (OSError, IOError):
        continue
