#!/usr/bin/env -S uv run --script
#MISE description="Set a frontmatter field value"
#USAGE arg "<field>" help="Field name to set"
#USAGE arg "<value>" help="Value to set"
#USAGE arg "<file>" help="Markdown file to modify"
# /// script
# dependencies = ["pyyaml"]
# ///

import os
import sys

sys.path.insert(0, os.environ["MISE_CONFIG_ROOT"] + "/lib")
from farts import set_field, resolve_path

field = os.environ["usage_field"]
value = os.environ["usage_value"]
path = resolve_path(os.environ["usage_file"])

with open(path) as f:
    text = f.read()

result = set_field(text, field, value)
with open(path, "w") as f:
    f.write(result)
